# Configuration Example for Changelog Generator
#
# For local usage, copy this file to .changelog.local.yaml:
#   cp .changelog.yaml .changelog.local.yaml
#
# Then edit .changelog.local.yaml to add your repository settings.
# .changelog.local.yaml is git-ignored and safe for local credentials.

# GitHub configuration (optional - can be set via flags or interactive prompt)
# Note: GITHUB_TOKEN should be set as environment variable for security
# repo_owner: facebook
# repo_name: react

# OpenAI configuration
# Note: OPENAI_API_KEY should be set as environment variable for security
openai_model: gpt-4o           # Model to use (gpt-4o, gpt-4, gpt-3.5-turbo)
max_tokens: 4000                # Maximum tokens for response
temperature: 0.3                # Lower = more focused, higher = more creative

# Output configuration
output_path: CHANGELOG.md       # Where to write the changelog
include_authors: true           # Include commit authors in output
include_dates: false            # Include commit dates in output

# Behavior
verbose: false                  # Enable verbose logging
